### ISSUE TITLE
useRef hook bug

### ISSUE THREAD

**Issue by isandeepkadam** [jherr/fcc-state#1]
Use the useRef hook to increment the id of each name object, which unpredictably increments the value. 
![image](https://user-images.githubusercontent.com/91077084/208152136-6d172133-8fea-4c61-bc52-6cde6c79b777.png)

**Comment by jherr** [comment]
This can happy with HMR and the magic that React does when React does module reloading in dev mode.

**Comment by Aljaetc** [comment]
native-useRef/src /App.jsx.
replace string 11-14

 const [names, setNames] = useState([
    { id: idRef.current++, name: "John" },
    { id: idRef.current++, name: "Jane" },
  ]);

with this

 const [names, setNames] = useState(() => ([
    { id: idRef.current++, name: "John" },
    { id: idRef.current++, name: "Jane" },
  ]));

Will this be the right solution for this bug?

**Comment by jherr** [comment]
Possibly, it's an HMR bug. It doesn't exist outside of that.
